# Generated by Django 3.0.5 on 2021-04-22 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('valuate', '0002_auto_20210422_2200'),
    ]

    operations = [
        migrations.AddField(
            model_name='uservaluationdetails',
            name='predicted_value',
            field=models.CharField(default=2020, max_length=50),
            preserve_default=False,
        ),
    ]
